import base64, functools

encoding = {
    "A": "ICAgICAgICAKICAgIyAgICAKICAjICMgICAKICMgICAjICAKIyMjIyMjIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "B": "ICAgICAgICAKIyMjIyMjICAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjICAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "C": "ICAgICAgICAKICMjIyMjICAKIyAgICAgIyAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgIyAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "D": "ICAgICAgICAKIyMjIyMgICAKIyAgICAjICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAjICAKIyMjIyMgICAKICAgICAgICAKICAgICAgICAK",
    "E": "ICAgICAgICAKIyMjIyMjIyAKIyAgICAgICAKIyAgICAgICAKIyMjIyMgICAKIyAgICAgICAKIyAgICAgICAKIyMjIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "F": "ICAgICAgICAKIyMjIyMjIyAKIyAgICAgICAKIyAgICAgICAKIyMjIyMgICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKICAgICAgICAKICAgICAgICAK",
    "G": "ICAgICAgICAKICMjIyMjICAKIyAgICAgIyAKIyAgICAgICAKIyAgIyMjIyAKIyAgICAgIyAKIyAgICAgIyAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "H": "ICAgICAgICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "I": "ICAgICAgICAKIyMjIyMjIyAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKIyMjIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "J": "ICAgICAgICAKIyMjIyMjIyAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKIyAgIyAgICAKICMjICAgICAKICAgICAgICAKICAgICAgICAK",
    "K": "ICAgICAgICAKIyAgICAgIyAKIyAgICAjICAKIyAgICMgICAKIyMjIyAgICAKIyAgICMgICAKIyAgICAjICAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "L": "ICAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyMjIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "M": "ICAgICAgICAKIyAgICAgIyAKIyMgICAjIyAKIyAjICMgIyAKIyAgIyAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "N": "ICAgICAgICAKIyAgICAgIyAKIyMgICAgIyAKIyAjICAgIyAKIyAgIyAgIyAKIyAgICMgIyAKIyAgICAjIyAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "O": "ICAgICAgICAKIyMjIyMjIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "P": "ICAgICAgICAKIyMjIyMjICAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKICAgICAgICAKICAgICAgICAK",
    "Q": "ICAgICAgICAKIyMjIyMjIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjIyAKICAgIyMgICAKICAgICMjIyAKICAgICAgICAKICAgICAgICAK",
    "R": "ICAgICAgICAKIyMjIyMjICAKIyAgICAgIyAKIyAgICAgIyAKIyMjIyMjICAKIyAgICMgICAKIyAgICAjICAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "S": "ICAgICAgICAKICMjIyMjICAKIyAgICAgIyAKIyAgICAgICAKICMjIyMjICAKICAgICAgIyAKIyAgICAgIyAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "T": "ICAgICAgICAKIyMjIyMjIyAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgICAgICAKICAgICAgICAK",
    "U": "ICAgICAgICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "V": "ICAgICAgICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICMgICAjICAKICAjICMgICAKICAgIyAgICAKICAgICAgICAKICAgICAgICAK",
    "W": "ICAgICAgICAKIyAgICAgIyAKIyAgIyAgIyAKIyAgIyAgIyAKIyAgIyAgIyAKIyAgIyAgIyAKIyAgIyAgIyAKICMjICMjICAKICAgICAgICAKICAgICAgICAK",
    "X": "ICAgICAgICAKIyAgICAgIyAKICMgICAjICAKICAjICMgICAKICAgIyAgICAKICAjICMgICAKICMgICAjICAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "Y": "ICAgICAgICAKIyAgICAgIyAKICMgICAjICAKICAjICMgICAKICAgIyAgICAKICAjICAgICAKICMgICAgICAKIyAgICAgICAKICAgICAgICAKICAgICAgICAK",
    "Z": "ICAgICAgICAKIyMjIyMjIyAKICAgICAjICAKICAgICMgICAKICAgIyAgICAKICAjICAgICAKICMgICAgICAKIyMjIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "a": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMgICAKICAgICAjICAKICMjIyMjICAKIyAgICAjICAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "b": "ICAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyMjIyMgICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKIyMjIyMgICAKICAgICAgICAKICAgICAgICAK",
    "c": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMjICAKIyAgICAgICAKIyAgICAgICAKIyAgICAgICAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "d": "ICAgICAgICAKICAgICAjICAKICAgICAjICAKICMjIyMjICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "e": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMgICAKIyAgICAjICAKIyMjIyMjICAKIyAgICAgICAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "f": "ICAgICAgICAKICAjIyMjICAKICAjICAgICAKIyMjIyMjICAKICAjICAgICAKICAjICAgICAKICAjICAgICAKICAjICAgICAKICAgICAgICAKICAgICAgICAK",
    "g": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMgICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKICMjIyMjICAKICAgICAjICAKIyMjIyMgICAK",
    "h": "ICAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyMjIyMgICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKICAgICAgICAKICAgICAgICAK",
    "i": "ICAgICAgICAKICAjIyMgICAKICAjIyMgICAKICAgICAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgICAgICAKICAgICAgICAK",
    "j": "ICAgICAgICAKICAjIyMgICAKICAjIyMgICAKICAgICAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKIyAgIyAgICAKIyAgIyAgICAKICMjICAgICAK",
    "k": "ICAgICAgICAKIyAgICAgICAKIyAgICAgICAKIyAgICMgICAKIyAgIyAgICAKIyMjICAgICAKIyAgIyAgICAKIyAgICMgICAKICAgICAgICAKICAgICAgICAK",
    "l": "ICAgICAgICAKIyMgICAgICAKICAjICAgICAKICAjICAgICAKICAjICAgICAKICAjICAgICAKICAjICAgICAKICAgIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "m": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjICMjICAKIyAgIyAgIyAKIyAgIyAgIyAKIyAgICAgIyAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "n": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMjICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICAgICAgICAKICAgICAgICAK",
    "o": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMjICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "p": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMgICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKIyMjIyMgICAKIyAgICAgICAKIyAgICAgICAK",
    "q": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMgICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKICMjIyMjICAKICAgICAjICAKICAgICAjICAK",
    "r": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyMgICMjICAKICMgIyAgICAKICMjICAgICAKICMgICAgICAKICMgICAgICAKICAgICAgICAKICAgICAgICAK",
    "s": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICMjIyMgICAKIyAgICAgICAKIyMjIyMgICAKICAgICMgICAKIyMjIyAgICAKICAgICAgICAKICAgICAgICAK",
    "t": "ICAgICAgICAKICAjIyAgICAKICAgIyAgICAKICMjIyMjIyAKICAgIyAgICAKICAgIyAgICAKICAgIyAgICAKICAgIyMjIyAKICAgICAgICAKICAgICAgICAK",
    "u": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKIyAgICAgIyAKICMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    "v": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyAgICAgIyAKIyAgICAgIyAKICMgICAjICAKICAjICMgICAKICAgIyAgICAKICAgICAgICAKICAgICAgICAK",
    "w": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyAgICAgIyAKIyAgICAgIyAKIyAgIyAgIyAKIyAgIyAgIyAKICMjICMjICAKICAgICAgICAKICAgICAgICAK",
    "x": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyAgICAjICAKICMgICMgICAKICAjIyAgICAKICMgICMgICAKIyAgICAjICAKICAgICAgICAKICAgICAgICAK",
    "y": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKIyAgICAjICAKICMjIyMjICAKICAgICAjICAKIyMjIyMgICAK",
    "z": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKIyMjIyMjICAKICAgIyMgICAKICAgIyAgICAKICMjICAgICAKIyMjIyMjICAKICAgICAgICAKICAgICAgICAK",
    ".": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKIyMjICAgICAKIyMjICAgICAKICAgICAgICAKICAgICAgICAK",
    " ": "ICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAKICAgICAgICAK",
}


def decode_and_split(text: str) -> list:
    lines = base64.b64decode(text.encode()).decode().split("\n")
    return lines


def join(ch1: list, ch2: list) -> list:
    new_list = list(map(lambda tup: tup[0] + tup[1], zip(ch1, ch2)))
    return new_list


def decode_and_concat(seq: list[str]) -> list:
    text = list(map(decode_and_split, seq))
    return functools.reduce(join, text)


def convert(seq: list) -> str:
    return "\n".join(decode_and_concat(seq))


def get_art(text: str) -> str:
    seq = [encoding[ch] for ch in text]
    return convert(seq)


if __name__ == "__main__":
    text = input("Enter your text here: ")
    print(get_art(text))
